class Book {
  constructor(category, subcategory, name, author, ID) {
      category = this.category,
      subcategory = this.subcategory,
      name = this.name,
      author = this.ID,
      ID = this.ID
  }
}

const array = [
  {
    category: "Fizyka",
    subcategory: "",
    name: "Fizyka I",
    author: "Openstax",
    ID: "46134304",
  },
  {
    category: "Fizyka",
    subcategory: "",
    name: "Fizyka II",
    author: "Openstax",
    ID: "68753662",
  },
  {
    category: "Fizyka",
    subcategory: "",
    name: "Fizyka III",
    author: "Openstax",
   ID: "21261204",
  },
  {
    category: "Fizyka",
    subcategory: "",
    name: "Podstawy Fizyki",
    author: "D. Halliday",
   ID: "33024527",
  },
  {
    category: "Fizyka",
    subcategory: "",
    name: "Fizyka ciała stałego",
    author: "Ch. Kittel",
    ID: "57517361",
  },
  {
    category: "Matematyka",
    subcategory: "",
    name: "Matematyka",
    author: "AGH Kraków",
    ID: "34911905",
  },
  {
    category: "Matematyka",
    subcategory: "",
    name: "Matematyka",
    author: "KUL Lublin",
    ID: "14503394",
  },
  {
    category: "Matematyka",
    subcategory: "Wstęp do Matematyki",
    name: "Wstęp do matematyki",
    author: "P. Jędrzejewicz",
    ID: "11749235",
  },
  {
    category: "Matematyka",
    subcategory: "Algebra",
    name: "Algebra liniowa I - Twierdzenia",
    author: "T. Jurlewicz, Z. Skoczylas",
    ID: "12970639",
  },
  {
    category: "Matematyka",
    subcategory: "Algebra",
    name: "Algebra liniowa I - Zadania",
    author: "T. Jurlewicz, Z. Skoczylas",
    ID: "70182534",
  },
  {
    category: "Matematyka",
    subcategory: "Algebra",
    name: "Algebra liniowa II - Twierdzenia",
    author: "T. Jurlewicz, Z. Skoczylas",
    ID: "37386105",
  },
  {
    category: "Matematyka",
    subcategory: "Algebra",
    name: "Algebra liniowa II - Zadania",
    author: "T. Jurlewicz, Z. Skoczylas",
    ID: "47390428",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Analiza Matematyczna I - Twierdzenia",
    author: "M. Gewert, Z. Skoczylas",
    ID: "45783883",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Analiza Matematyczna I - Zadania",
    author: "M. Gewert, Z. Skoczylas",
    ID: "56547275",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Analiza Matematyczna II - Twierdzenia",
    author: "M. Gewert, Z. Skoczylas",
    ID: "26288175",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Analiza Matematyczna II - Zadania",
    author: "M. Gewert, Z. Skoczylas",
    ID: "61686802",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Rachunek Różniczkowy i Całkowy I",
    author: "G. M. Fichtenholz",
   ID: "28366672",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Rachunek Różniczkowy i Całkowy II",
    author: "G. M. Fichtenholz",
   ID: "33564216",
  },
  {
    category: "Matematyka",
    subcategory: "Analiza Matematyczna",
    name: "Rachunek Różniczkowy i Całkowy III",
    author: "G. M. Fichtenholz",
    ID: "73064207",
  },
  {
    category: "Matematyka",
    subcategory: "Matematyka Dyskretna",
    name: "Matematyka Dyskretna",
    author: "K. Ross",
    ID: "66287388",
  },
  {
    category: "Informatyka",
    subcategory: "",
    name: "C# - Praktyczny kurs",
    author: "M. Lis",
    ID: "52270699",
  },
  {
    category: "Informatyka",
    subcategory: "",
    name: "Szkoła programowania w C++",
    author: "S. Prata",
    ID: "39331449",
  },
  {
    category: "Informatyka",
    subcategory: "",
      name: "Język Go - poznaj i programuj",
      author: "A. Donovan",

  
      ID: "37209230",
  },
  {
    category: "Informatyka",
    subcategory: "",
    name: "Python - programuj szybko i wydajnie",
    author: "M. Goelick",
    ID: "66770043",
  },
  {
    category: "Informatyka",
    subcategory: "",
    name: "Dart i Flutter dla początkujących",
    author: "A. Biessek",
    ID: "54659425",
  },
  {
    category: "Elektronika",
    subcategory: "",
    name: "Podstawy Elektroniki",
    author: "???",
    ID: "61977616",
  },
  {
    category: "Elektronika",
    subcategory: "",
      name: "Podstawy Elektroniki",
      author: "Politechnika Wrocławska",

  
      ID: "33690110",
  },
  {
    category: "Elektronika",
    subcategory: "",
    name: "Sztuka Elektroniki 2 Tomy",
    author: "P. Horowitz",
    ID: "74992378",
  },
  {
    category: "Inżynieria Kwantowa",
    subcategory: "",
    name: "Mechanika Kwantowa",
    author: "S. Kryszewski",
   ID: "15318404",
  },
  {
    category: "Inżynieria Kwantowa",
    subcategory: "",
    name: "Wykłady z mechaniki kwantowej",
    author: "R. Feynman",
    ID: "29351995",
  },
  {
    category: "Inżynieria Kwantowa",
    subcategory: "",
    name: "Wstęp do informatyki kwantowej",
    author: "M. Le Bellac",
   ID: "33027531",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Biologia Campbella",
    author: "N. Campbell",
    ID: "28705997",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Kompendium Neurologii",
    author: "R. Podemski",
   ID: "25377623",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Krótkie wykłady z neurolobiologii",
    author: "A. Longstaff",
   ID: "18446218",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Krótkie wykłady z mikrobiologii",
    author: "J. Nicklin",
    ID: "65389971",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Biofizyka dla studentów",
    author: "F. Jaroszyk",
    ID: "18345725",
  },
  {
    category: "Biologia",
    subcategory: "",
    name: "Biochemia",
    author: "J. M. Berg",
    ID: "38958949",
  },
  {
    category: "Chemia",
    subcategory: "",
    name: "Chemia fizyczna",
    author: "P. Atkins",
    ID: "27514290",
  },
  {
    category: "Chemia",
    subcategory: "",
    name: "Chemia ogólna",
    author: "L. Jones, P. Atkins",
    ID: "72291567",
  },
  {
    category: "Chemia",
    subcategory: "",
    name: "Chemia organiczna",
    author: "J. McMurry",
    ID: "57119375",
  },
  {
    category: "Psychologia",
    subcategory: "",
    name: "Psychologia - Kluczowe koncepcje tom I",
    author: "P. Zimbardo",
    ID: "66648907",
  },
  {
    category: "Psychologia",
    subcategory: "",
    name: "Psychologia - Kluczowe koncepcje tom II",
    author: "P. Zimbardo",
    ID: "51936913",
  },
  {
    category: "Psychologia",
    subcategory: "",
    name: "Psychologia - Kluczowe koncepcje tom III",
    author: "P. Zimbardo",
    ID: "62329168",
  },
  {
    category: "Psychologia",
    subcategory: "",
    name: "Psychologia - Kluczowe koncepcje tom IV",
    author: "P. Zimbardo",
    ID: "78338516",
  },
  {
    category: "Psychologia",
    subcategory: "",
    name: "Psychologia - Kluczowe koncepcje tom V",
    author: "P. Zimbardo",
    ID: "43656557",
  },
  {
    category: "Filozofia",
    subcategory: "",
    name: "Filozofia dla bystrzaków",
    author: "T. Morris",
    ID: "39889503",
  },
  {
    category: "Pozostałe",
    subcategory: "",
    name: "Lemegeton",
    author: "Salomon",
   ID: "30651537",
  },
  {
    category: "Pozostałe",
    subcategory: "",
    name: "Mein Kampf",
    author: "A. Hitler",
   ID: "23382005",
  },
]

let books = []
array.forEach((bookData) => books.push(new Book(bookData)));

module.exports = {
  array,
  Book
}